import Mock from 'mockjs'

let list=[]
export default{
    getStatisticalData:() =>{
        for(let i=0;i<7;i++){
            list.push(
                Mock.mock({
                    セルフレーム:Mock.Random.float(100,8000,0,0),
                    メタルフレーム:Mock.Random.float(100,8000,0,0),
                    軽量メガネ:Mock.Random.float(100,8000,0,0),
                    サングラス:Mock.Random.float(100,8000,0,0),
                    PCメガネ:Mock.Random.float(100,8000,0,0),
                    老眼鏡:Mock.Random.float(100,8000,0,0),
                })
            )
        }
        return{
            code:2000,
            data:{
               videoData:[
                {
                    name:'セルフレーム',
                    value:'275500'
                },
                {
                    name:'メタルフレーム',
                    value:'158400'
                },
                {
                    name:'軽量メガネ',
                    value:'532800'
                },
                {
                    name:'サングラス',
                    value:'122100'
                },
                {
                    name:'PCメガネ',
                    value:'110000'
                },
                {
                    name:' 老眼鏡',
                    value:'48400'
                }
               ],
               userData:[
                {
                    date:'月曜日',
                    new:20,
                    active:5
                },
                {
                    date:'火曜日',
                    new:25,
                    active:7
                },
                {
                    date:'水曜日',
                    new:27,
                    active:4
                },
                {
                    date:'木曜日',
                    new:34,
                    active:8
                },
                {
                    date:'金曜日',
                    new:43,
                    active:10
                },
                {
                    date:'土曜日',
                    new:56,
                    active:12
                },
                {
                    date:'日曜日',
                    new:50,
                    active:9
                },
               ],
               orderData:{
                date:['20221001','20221002','20221003','20221004','20221005','20221006','20221007'],
                data:list
               },
               tableData:[
                {
                    name:'セルフレーム',
                    todayBuy:'5,500',
                    monthBuy:'44,000',
                    totalBuy:'275,500'
                  },
                  {
                    name:'メタルフレーム',
                    todayBuy:'8,800',
                    monthBuy:'79,200',
                    totalBuy:'158,400'
                  },
                  {
                    name:'軽量メガネ',
                    todayBuy:'444,000',
                    monthBuy:'165,500',
                    totalBuy:'532,800'
                  },
                  {
                    name:'サングラス',
                    todayBuy:'6,600',
                    monthBuy:'26,400',
                    totalBuy:'122,100'
                  },
                  {
                    name:'PCメガネ',
                    todayBuy:'5,500',
                    monthBuy:'27,500',
                    totalBuy:'110,000'
                  },
                  {
                    name:'老眼鏡',
                    todayBuy:'0',
                    monthBuy:'4400',
                    totalBuy:'48,400'
                  }
                ]
            }
        }
    }
}